### ISSUE TITLE
missing page

### ISSUE THREAD

**Issue by szabgab** [OSDC-Code-Maven/open-source-by-organizations#70]
From this list of New Zealand https://osdc.code-maven.com/open-source-by-organizations/loc/new-zealand the link to CMOR is this
https://osdc.code-maven.com/open-source-by-organizations/loc/github/uo-cmor but it is 404

**Comment by KetanParmar02** [comment]
Hey, @szabgab i'm interested to resolve this issue can you assign to me?
so, i can resolve this issue and contribute in your project..
i hope you will give me this opportunity.

**Comment by szabgab** [comment]
go ahead, just do it

**Comment by KetanParmar02** [comment]
can you suggest me what should I do next now??

**Comment by szabgab** [comment]
I just followed the instructions in the bug-report and it does not happen any more. I guess it is already fixed.
